language: python

sudo: false

os: linux
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - g++-7
      - gcc-7
      - cmake
      - python3.6-dev
      - python3.4-dev
      - libnetcdf-dev


matrix:
  include:
    - python: 3.6
      name: "3.6"
      env:
        - CXX=g++-7
        - CC=gcc-7

    - python: 3.4
      name: "3.4"
      env:
        - CXX=g++-7
        - CC=gcc-7

before_script:
  - git clone https://github.com/sizmailov/pyxmopp_tests_dataset.git tests_dataset
  - python -m pip install flake8
  - export CXX ; export CC
  - python setup.py install

script:
  - python -m pytest