language: python

sudo: false

os: linux
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake
      - libnetcdf-dev

matrix:
  include:
    - python: 3.6
      name: "3.6"

#    - python: 3.4
#      name: "3.4"

before_script:
  - git clone https://github.com/sizmailov/pyxmopp_tests_dataset.git tests_dataset
  - python -m pip install flake8
  - python setup.py install

script:
  - python -m pytest