language: python

sudo: false

os: linux
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - g++-7
      - gcc-7
      - cmake
      - python3.7-dev
      - python3.5-dev
      - libnetcdf-dev


matrix:
  include:
    - python: 3.7
      name: "python 3.7, g++-7"
      env:
        - CXX=g++-7
        - CC=gcc-7

    - python: 3.5
      name: "python 3.5, g++-7"
      env:
        - CXX=g++-7
        - CC=gcc-7

before_script:
  - python -m pip install flake8 mypy
  - python -m flake8
  - git clone https://github.com/sizmailov/pyxmopp_tests_dataset.git tests_dataset
  - export CXX ; export CC
  - python setup.py install
  - python -m pip install pyxmolpp2-stubs # for mypy

script:
  - python -m mypy bionmr_utils --ignore-missing-imports
  - python -m pytest